platform :ios,'8.0'
use_frameworks!

target 'HelloSwfit' do
pod 'AFNetworking','~> 3.0'
pod 'SwiftyJSON','~> 2.3'
pod 'SDWebImage', '~>3.7'
pod  'MJRefresh'
pod 'Toast-Swift', '~> 1.3.0'
pod 'AlamofireNetworkActivityIndicator', '~> 1.0'
pod 'MBProgressHUD', '~> 0.9.2'

end
